image: ubuntu:latest

default:
  before_script:
    - apt-get -y update
    - apt-get install -y libmagic-dev
    - apt -y install net-tools python3 python3-pip mysql-client
    - cd django-backend
    - pip3 install -r requirements_gitlab.txt
    

migrations:
  stage: build
  script:
    - python3 manage.py makemigrations
    - python3 manage.py migrate
    - python3 manage.py check


django-tests:
  stage: test
  script:
    - coverage run manage.py test
    - coverage report
    - coverage xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
